[package]
name = "cli"
version = "0.1.0"
edition = "2018"
authors = ["Tuan Vuong <vanhtuan0409@gmail.com>"]

[[bin]]
name = "toon"
path = "src/main.rs"

[dependencies]
clap = "3.0.0-beta.2"
toon-core = { path = "../toon-core" }
