[package]
name = "toon-core"
version = "0.1.0"
edition = "2018"

[dependencies]
tree-sitter = "0.19.5"
tree-sitter-toon = { path = "../tree-sitter-toon" }
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm12-0"] }
tempfile = "3.2.0"
snailquote = "0.3.0"
